#!/bin/bash
#
# Build RPM
#
# @author Jun Futagawa (jfut)

BUILD_PACKAGES="autoconf automake libtool gcc make rpm-build rpmdevtools"
MAX_RETRY="10"

if [[ $# -lt 2 ]]; then
    echo $0 RPMBUILD_DIR SPEC_FILE_NAME
    exit 1
fi

RPMBUILD_DIR="$1"
SPEC_FILE_NAME="$2"

export LC_ALL=C

pushd "${RPMBUILD_DIR}"

# RPM macros
RPM_MACROS=/usr/lib/rpm/macros.d/macros.dist
if [[ -f /etc/rpm/macros.dist ]]; then
    # el8
    RPM_MACROS=/etc/rpm/macros.dist
fi
RPM_DIST=.$(grep -E -o "^%el[0-9]*" "${RPM_MACROS}" | tr -d '%')
echo "RPM_DIST: ${RPM_DIST} (${RPM_MACROS})"

# install dependencies
if [[ -f /usr/bin/dnf ]]; then
    # el8 or later
    echo
    echo "Installing build tools and dependencies: ${BUILD_PACKAGES} dnf-plugins-core"
    RETRY=0
    until dnf -y install ${BUILD_PACKAGES} dnf-plugins-core || [[ "${RETRY}" -eq "${MAX_RETRY}" ]];
    do
        echo
        sleep $((RETRY++))
        echo "Retry: dnf -y install ${BUILD_PACKAGES} (retry: ${RETRY})"
    done
    until dnf -y builddep "SPECS/${SPEC_FILE_NAME}" || [[ "${RETRY}" -eq "${MAX_RETRY}" ]];
    do
        sleep $((RETRY++))
        echo
        echo "Retry: dnf -y builddep \"SPECS/${SPEC_FILE_NAME}\" (retry: ${RETRY})"
    done
else
    echo
    echo "Installing build tools and dependencies: ${BUILD_PACKAGES}"
    until yum -y install ${BUILD_PACKAGES} || [[ "${RETRY}" -eq "${MAX_RETRY}" ]];
    do
        sleep $((RETRY++))
        echo
        echo "Retry: yum -y install ${BUILD_PACKAGES} (retry: ${RETRY})"
    done
    until yum-builddep -y "SPECS/${SPEC_FILE_NAME}" || [[ "${RETRY}" -eq "${MAX_RETRY}" ]];
    do
        sleep $((RETRY++))
        echo
        echo "Retry: yum-builddep -y \"SPECS/${SPEC_FILE_NAME}\" (retry: ${RETRY})"
    done
fi

# build rpm
if [[ ! -d SOURCES ]]; then
    mkdir SOURCES
fi

if [[ "${RPM_DIST}" = ".el8" ]]; then
    # el8
    spectool -g -A "SPECS/${SPEC_FILE_NAME}" -C SOURCES/
else
    # el9 or later
    spectool -g -a "SPECS/${SPEC_FILE_NAME}" -C SOURCES/
fi

echo "Building RPM:"
rpmbuild \
    --define "%_topdir ${RPMBUILD_DIR}" \
    --define "%dist ${RPM_DIST}" \
    -ba "SPECS/${SPEC_FILE_NAME}"

popd

